/* Generated By:JavaCC: Do not edit this line. AutodetectionParserConstants.java */
package es.uvigo.ei.sing.alter.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AutodetectionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int BLANK = 2;
  /** RegularExpression Id. */
  int UPPER_CASE = 3;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int ANY = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "<BLANK>",
    "<UPPER_CASE>",
    "<NUMBER>",
    "<ANY>",
    "\"#\"",
    "\"%\"",
    "\"#NEXUS\"",
    "\"CLUSTAL\"",
    "\"MUSCLE\"",
    "\"PROBCONS\"",
    "\">\"",
    "\";\"",
    "\"PileUp\"",
    "\"!!AA_MULTIPLE_ALIGNMENT\"",
    "\"!!NA_MULTIPLE_ALIGNMENT\"",
  };

}
