/* Generated By:JavaCC: Do not edit this line. NexusParserConstants.java */
package es.uvigo.ei.sing.alter.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NexusParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int BLANK = 2;
  /** RegularExpression Id. */
  int UPPER_CASE = 3;
  /** RegularExpression Id. */
  int LOWER_CASE = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int ANY = 6;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "<BLANK>",
    "<UPPER_CASE>",
    "<LOWER_CASE>",
    "<NUMBER>",
    "<ANY>",
    "\"[\"",
    "<token of kind 8>",
    "\"]\"",
    "\"#NEXUS\"",
    "\";\"",
    "\"-\"",
    "\".\"",
    "\"?\"",
    "\"ntax\"",
    "\"nchar\"",
    "\"datatype\"",
    "\"matrix\"",
    "\"end;\"",
    "\"=\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"BEGIN DATA\"",
    "\"BEGIN TAXA\"",
    "\"BEGIN CHARACTERS\"",
  };

}
